# SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proxy",
    srcs = [
        "director.go",
        "h1.go",
        "h2.go",
        "h3.go",
        "health.go",
        "hijack.go",
        "proxy.go",
        "tracing.go",
    ],
    importpath = "nvcf-grpc-proxy/proxy",
    visibility = ["//visibility:public"],
    deps = [
        "//src/invocation-plane-services/grpc-proxy/nvcf/pb",
        "//src/invocation-plane-services/grpc-proxy/proxy/consts",
        "//src/invocation-plane-services/grpc-proxy/proxy/credentials",
        "//src/invocation-plane-services/grpc-proxy/proxy/geo",
        "//src/invocation-plane-services/grpc-proxy/proxy/hacks",
        "//src/invocation-plane-services/grpc-proxy/proxy/invocation",
        "//src/invocation-plane-services/grpc-proxy/proxy/metrics",
        "//src/invocation-plane-services/grpc-proxy/proxy/middleware",
        "//src/invocation-plane-services/grpc-proxy/proxy/quicconn",
        "//src/invocation-plane-services/grpc-proxy/proxy/ratelimit",
        "//src/invocation-plane-services/grpc-proxy/proxy/reloadableTls",
        "//src/invocation-plane-services/grpc-proxy/proxy/worker",
        "@com_github_carlmjohnson_versioninfo//:versioninfo",
        "@com_github_go_chi_cors//:cors",
        "@com_github_google_uuid//:uuid",
        "@com_github_hellofresh_health_go_v5//:health-go",
        "@com_github_jellydator_ttlcache_v3//:ttlcache",
        "@com_github_nats_io_nats_go//:nats_go",
        "//src/libraries/go/lib/pkg/nvkit/auth",
        "//src/libraries/go/lib/pkg/nvkit/clients",
        "//src/libraries/go/lib/pkg/nvkit/errors",
        "//src/libraries/go/lib/pkg/nvkit/logs",
        "//src/libraries/go/lib/pkg/nvkit/servers",
        "//src/libraries/go/lib/pkg/nvkit/tracing",
        "@com_github_nvidia_nvcf_src_libraries_go_lib//pkg/version",
        "@com_github_quic_go_quic_go//:quic-go",
        "@com_github_quic_go_quic_go//http3",
        "@com_github_samber_lo//:lo",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel//semconv/v1.24.0:v1_24_0",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//health/grpc_health_v1",
        "@org_golang_google_grpc//status",
        "@org_golang_x_net//http2",
        "@org_golang_x_net//http2/h2c",
        "@org_uber_go_zap//:zap",
    ],
)

alias(
    name = "go_default_library",
    actual = ":proxy",
    visibility = ["//visibility:public"],
)

go_test(
    name = "proxy_test",
    srcs = [
        "connection_logging_test.go",
        "director_test.go",
        "hijack_test.go",
        "info_test.go",
        "pending_work_test.go",
        "proxy_test.go",
    ],
    embed = [":proxy"],
    deps = [
        "//src/invocation-plane-services/grpc-proxy/proxy/consts",
        "//src/invocation-plane-services/grpc-proxy/proxy/internal/echo",
        "//src/invocation-plane-services/grpc-proxy/proxy/internal/test",
        "//src/invocation-plane-services/grpc-proxy/proxy/invocation",
        "//src/invocation-plane-services/grpc-proxy/proxy/metrics",
        "//src/invocation-plane-services/grpc-proxy/proxy/worker",
        "@com_github_carlmjohnson_versioninfo//:versioninfo",
        "@com_github_google_uuid//:uuid",
        "@com_github_gorilla_websocket//:websocket",
        "@com_github_hellofresh_health_go_v5//:health-go",
        "@com_github_jellydator_ttlcache_v3//:ttlcache",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//metadata",
        "@org_golang_x_sync//errgroup",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zaptest/observer",
    ],
)
